# Generated by Django 4.2 on 2023-05-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=255)),
                ('options', models.CharField(choices=[('doctorappointment', 'doctorappointment'), ('labtest', 'labtest')], max_length=20)),
                ('message', models.TextField()),
                ('upload', models.FileField(upload_to='')),
            ],
        ),
    ]
